stages:
  stage_getting_pretrained_model:
    cmd: python src/get_pretrained_model.py
    deps:
    - src/get_pretrained_model.py
    outs:
    - data/model.h5
  stage_evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/imagenet_v2
    - data/model.h5
    - src/evaluate.py
    - src/load_test_dataset.py
    metrics:
    - data/eval.json
