# This is a basic workflow to help you get started with Actions

name: evaluate

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Evaluate model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install requirements
          pip install -r requirements.txt
          
          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull --run-cache
          dvc repro
          
          echo dvc metrics show
          
          
          
