name: test minimal accuracy

on: [push, workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:  [3.9]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Prepare dvc and pull data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          dvc pull --run-cache -q
        
      - name: Evaluate model
        run: |
          dvc repro
      
      - name: Show metrics
        run: |
          dvc metrics show
      
      - name: Test with pytest
        run: |
          python tests/minimal_accuracy.py
