name: test minimal accuracy

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:  [3.9]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Prepare dvc and pull data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Install requirements
          pip install -r requirements.txt
          
          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull --run-cache -q
      - name: Evaluate model
        run: |
          dvc repro
      
      - name: Show metrics
        run: |
          dvc metrics show
      - name: Test with pytest
        run: |
          python tests/minimal_accuracy.py
